#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

$(git diff --cached  $against | git-felony)
felons=${PIPESTATUS[0]}
if [[ $felons -ne 0 ]];
then
	cat <<\EOF
Looks like you're about to commit files containing illegal content
EOF
    exit 1
fi
